### ISSUE TITLE
about the template

### ISSUE THREAD

**Issue by vicbp1** [23andMe/phasedibd#3]
Hi, 
I would like to know if changing the template to
 [[1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]
 like this:
tpbwt = ibd.TPBWTAnalysis(template=[[1, 0, 0, 0],
                                    [0, 1, 0, 0],
                                    [0, 0, 1, 0],
                                    [0, 0, 0, 1]])

means that I will allow a lower proportion of errors?

I run a test with the default and with this modified template and I was expect a lower amount of IBD segments for the modified version. Actually, I found a larger amount of IBD segments for the modified version. I am doing something wrong?

Thank you in advanve

**Comment by wf8** [comment]
The templates you propose:
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
allow for more errors than the default templates. They allow for "fuzzier" matching so you got more segments.

I recommend you try these templates:
[[0, 1, 1, 1],
[1, 0, 1, 1],
[1, 1, 0, 1],
[1, 1, 1, 0]]
These require stricter matches (fewer errors).
